const commodityOptions = [
    { id: 1, name: "LAPTOP" },
    { id: 2, name: "MOBILE" },
    { id: 3, name: "CAMERA" },
    { id: 4, name: "MP3 PLAYER" },
    { id: 5, name: "PENDRIVE" },
    { id: 6, name: "GIFT PACK" },
    { id: 8, name: "LAPTOP/BATTERY" },
    { id: 9, name: "POWER CARD" },
    { id: 10, name: "CARRY BAG" },
    { id: 11, name: "BATERY" },
    { id: 12, name: "MOUSE" },
    { id: 13, name: "CD/MANUALS" },
    { id: 14, name: "GIFT BOX" },
    { id: 15, name: "RAKHI" },
    { id: 16, name: "MOBILE - APPLE" },
    { id: 17, name: "ARTIFICIAL JEWELLERY" },
    { id: 18, name: "MANUALS" },
    { id: 19, name: "CHARGER" },
    { id: 20, name: "AUTO PARTS" },
    { id: 21, name: "EAR PHONE" },
    { id: 22, name: "SD CARD" },
    { id: 23, name: "USB CABLE" },
    { id: 24, name: "SEEDS" },
    { id: 25, name: "INTERNATIONAL CONTENT" },
    { id: 26, name: "PERFUMES" },
    { id: 27, name: "LAPTOP BAG" },
    { id: 28, name: "HIGH END CAMERA" },
    { id: 29, name: "BATTERY (PHONE/ LAPTOP/ POWERBANK)" },
    { id: 30, name: "BACK UP BATERY" },
    { id: 31, name: "COVER" },
    { id: 32, name: "UPS" },
    { id: 33, name: "CDs" },
    { id: 35, name: "CHOCOLATES" },
    { id: 36, name: "GREETING CARD" },
    { id: 37, name: "TOYS" },
    { id: 38, name: "CLOTHING" },
    { id: 39, name: "LIQUID CHEMICAL (EG: SANITISER ETC)" },
    { id: 40, name: "POWER CABLES" },
    { id: 41, name: "CARRY CASE" },
    { id: 42, name: "FURNITURE1" },
    { id: 43, name: "HOUSE HOLD GOODS" },
    { id: 44, name: "CORPORATE GIFTS (EG: MOMENTOES/ WOODEN PLAQUES)" },
    { id: 45, name: "PAINTING/ ARTWORK ROLL" },
    { id: 46, name: "SIM CARD/ SD CARD" },
    { id: 47, name: "HOME APPLIANCES" },
    { id: 48, name: "MEDICAL EQUIPMENT" },
    { id: 49, name: "FOOD ITEMS1" },
    { id: 50, name: "PASSPORT" },
    { id: 51, name: "GLASS ITMES" },
    { id: 52, name: "TEA BAGS" },
    { id: 54, name: "SPICES" },
    { id: 55, name: "FRUIT BOX" },
    { id: 56, name: "UNSTITCHED FABRIC" },
    { id: 57, name: "CREDIT/ DEBIT CARD" },
    { id: 58, name: "PERFUME" },
    { id: 59, name: "PROMOTIONAL MATERIAL (PAPER)" },
    { id: 60, name: "Mango Fruit" },
    { id: 61, name: "MUSIC CD" },
    { id: 62, name: "CPU" },
    { id: 63, name: "Greetings Card" },
    { id: 64, name: "DESKTOP" },
    { id: 65, name: "CLOTHING1" },
    { id: 66, name: "MASALA POWER PACK" },
    { id: 67, name: "SHOWES/SLIPPERS" },
    { id: 68, name: "VEHICLE PARTS" },
    { id: 69, name: "Liquid" },
    { id: 70, name: "Powder" },
    { id: 71, name: "DRY FRUITS" },
    { id: 72, name: "BOOKS" },
    { id: 73, name: "DOCUMENTS BOX" },
    { id: 74, name: "TABLETS" },
    { id: 75, name: "SWEETS" },
    { id: 76, name: "FOOD ITEMS" },
    { id: 77, name: "COMPUTER PARTS" },
    { id: 79, name: "LED LCD TV" },
    { id: 80, name: "LED LIGHTS" },
    { id: 81, name: "MEDICINE" },
    { id: 82, name: "GARMETS" },
    { id: 83, name: "ELECTRONIC ITEMS" },
    { id: 84, name: "PLASTIC ITEMS" },
    { id: 85, name: "FURNITURE" },
    { id: 86, name: "MONITOR" },
    { id: 87, name: "STATIONERY" },
    { id: 88, name: "MOBILE(WITHOUT BATTERY)" },
    { id: 89, name: "PHOTO FRAME" },
    { id: 90, name: "FARMING RELATED ITEEMS" },
    { id: 91, name: "ELECTRONIC ITEM(e.g Laptop LED)" },
    { id: 92, name: "GARMENTS CLOTHES" },
    { id: 93, name: "GIFT ITEMS" },
    { id: 94, name: "BAGS" },
    { id: 95, name: "BUNCH OF DOCUMENTS" },
    { id: 96, name: "SURGICAL PARTS" },
    { id: 97, name: "BODY COVER(e.g MOBILE CAR)" },
    { id: 98, name: "ARTIFICIAL ITEMS" },
  ];

  module.exports = commodityOptions;