
const DTDCStatusMapping = {
  "order received": "Ready To Ship",
  "pickup failed": "Ready To Ship",
  "pickup awaited": "Ready To Ship",
  "softdata upload": "Ready To Ship",
  "pickup scheduled": "Ready To Ship",
  "not picked": "Ready To Ship",
  "pickup reassigned": "Ready To Ship",
  "picked up": "In-transit",
  "shipment under investigation": "In-transit",
  booked: "In-transit",
  "in transit": "In-transit",
  "received after cut-off":"In-transit",
  "reached at destination": "In-transit",
  "mis route": "In-transit",
  "fdm prepared": "In-transit",
  "wrong pincode": "In-transit",
  "waiting for rto approval from origin": "In-transit",
  "non serviceable location": "In-transit",
  "disturbed/ prohibited area": "In-transit",
  "e-waybill dispute": "In-transit",
  "booking not updated": "In-transit",
  "shipment received after cut-off time at destination": "In-transit",
  "off-loaded by airlines (central team access)": "In-transit",
  "weekly off": "In-transit",
  "stock scan": "In-transit",
  "offload at origin": "In-transit",
  "received at delivery centre": "In-transit",
  "restricted delivery hours":"In-transit",
  "vehicle held in check post for inspection":"In-transit",
  "linehaul delayed road block / traffic jam":"In-transit",
  damaged: "Damaged",
  "out for delivery": "Out for Delivery",
  "otp based delivered": "Delivered",
  delivered: "Delivered",
  "not delivered": "Undelivered",
  "set rto initiated": "Undelivered",
  "rto processed & forwarded": "RTO",
  "return as per client instruction.": "RTO",
  "rto booked": "RTO",
  "rto in transit": "RTO In-transit",
  "rto received at delivery centre":"RTO In-transit",
  "rto reached at destination": "RTO In-transit",
  "rto fdm prepared": "RTO In-transit",
  "rto not delivered": "RTO In-transit",
  "rto out for delivery": "RTO In-transit",
  "rto mis route": "RTO In-transit",
  "shipment received short": "RTO In-transit",
  "rto delivered": "RTO Delivered",
};

module.exports = DTDCStatusMapping;
